language: python
python:
  - "2.6"
  - "2.7"
services:
  - couchdb
before_script:
  - pip install coveralls unittest2 nose-testconfig
script:
  - python setup.py install
  - nosetests tests --with-coverage --cover-package=couchapp --cover-html
after_success:
  - coveralls
